# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Slides"
  url = "https://www.canva.com/design/DADpbhfNT8s/n3lVBf4NviISxefyp9EuZQ/view?utm_content=DADpbhfNT8s&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
  weight = 20

[[main]]
  name = "Resources"
  url = "#talks"
  weight = 30
  
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 40

[[main]]
 name = "Worksheet"
 url = "cv.pdf"
 weight = 50
